version: '3.1'

services:

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: students
      MYSQL_USER: students
      MYSQL_PASSWORD: students
